build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: "RustPlusPlus Discord Bot"
  org.opencontainers.image.description: "A Discord bot for Rust+ Companion App integration"
  org.opencontainers.image.source: "https://github.com/alexemanuelol/rustplusplus"
  org.opencontainers.image.licenses: "GPL-3.0"
args:
  RUSTPLUSPLUS_VERSION: "1.22.0"