name: RustPlusPlus Discord Bot
version: "1.2.1"
slug: rustplusplus
description: A Discord bot that connects to Rust game servers via the Rust+ Companion App
url: https://github.com/alexemanuelol/rustplusplus
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual
init: false
options:
  discord_client_id: ""
  discord_token: ""
  log_level: info
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_discovery: true
schema:
  discord_client_id: str
  discord_token: password
  log_level: list(debug|info|warning|error)?
  mqtt_host: str?
  mqtt_port: int?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_discovery: bool?
