module.exports = {
    afk: { syntax: ['commandSyntaxAfk'] },
    alive: { syntax: ['commandSyntaxAlive'] },
    cargo: { syntax: ['commandSyntaxCargo'] },
    chinook: { syntax: ['commandSyntaxChinook'] },
    connection: { syntax: ['commandSyntaxConnection', 'commandSyntaxConnections'] },
    craft: { syntax: ['commandSyntaxCraft'] },
    death: { syntax: ['commandSyntaxDeath', 'commandSyntaxDeaths'], notPossibleDiscord: true },
    decay: { syntax: ['commandSyntaxDecay'] },
    despawn: { syntax: ['commandSyntaxDespawn'] },
    events: { syntax: ['commandSyntaxEvents'] },
    heli: { syntax: ['commandSyntaxHeli'] },
    large: { syntax: ['commandSyntaxLarge'] },
    leader: { syntax: ['commandSyntaxLeader'] },
    marker: { syntax: ['commandSyntaxMarker', 'commandSyntaxMarkers'], notPossibleDiscord: true },
    market: { syntax: ['commandSyntaxMarket'] },
    mute: { syntax: ['commandSyntaxMute'] },
    note: { syntax: ['commandSyntaxNote', 'commandSyntaxNotes'] },
    offline: { syntax: ['commandSyntaxOffline'] },
    online: { syntax: ['commandSyntaxOnline'] },
    player: { syntax: ['commandSyntaxPlayer', 'commandSyntaxPlayers'] },
    pop: { syntax: ['commandSyntaxPop'] },
    prox: { syntax: ['commandSyntaxProx'], notPossibleDiscord: true },
    recycle: { syntax: ['commandSyntaxRecycle'] },
    research: { syntax: ['commandSyntaxResearch'] },
    send: { syntax: ['commandSyntaxSend'], notPossibleDiscord: true },
    small: { syntax: ['commandSyntaxSmall'] },
    stack: { syntax: ['commandSyntaxStack'] },
    steamid: { syntax: ['commandSyntaxSteamid'] },
    team: { syntax: ['commandSyntaxTeam'] },
    time: { syntax: ['commandSyntaxTime'] },
    timer: { syntax: ['commandSyntaxTimer', 'commandSyntaxTimers'] },
    translateTo: { syntax: ['commandSyntaxTranslateTo'] },
    translateFromTo: { syntax: ['commandSyntaxTranslateFromTo'] },
    tts: { syntax: ['commandSyntaxTTS'] },
    unmute: { syntax: ['commandSyntaxUnmute'] },
    upkeep: { syntax: ['commandSyntaxUpkeep'] },
    uptime: { syntax: ['commandSyntaxUptime'] },
    wipe: { syntax: ['commandSyntaxWipe'] },
    travelingVendor: { syntax: ['commandSyntaxTravelingVendor'] },
};
